server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/startup
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: none

  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
    syntax-highlight:
      theme: dark
      activated: true

cors:
  originPatterns: http://localhost:8080,https://dev.rqsolutions.com.br

file:
  upload-dir: /Users/rodri/dev/cursos/rest_springboot/uploads